### ISSUE TITLE
大佬，我用react重新写了下发现如下图问题

### ISSUE THREAD

**Issue by ISBN9527** [xiejunping/andt-components#3]
![image](https://user-images.githubusercontent.com/30942709/124266900-247b2a80-db6a-11eb-85d3-ce286128bbf5.png)

上下有偏移可能是什么问题呢？

**Comment by ISBN9527** [comment]
@xiejunping

**Comment by ISBN9527** [comment]
![image](https://user-images.githubusercontent.com/30942709/124267380-c0a53180-db6a-11eb-81ce-50317969b9e8.png)

**Comment by xiejunping** [comment]
这应该是样式问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiejunping/andt-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 晚上7:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xiejunping/andt-components] 大佬，我用react重新写了下发现如下图问题 (#3)





 

 
上下有偏移可能是什么问题呢？

**Comment by xiejunping** [comment]
这里是半小时的维度，还是一小时维度，如果要半小时的，注意还有单元格应该有合并的地方要去掉，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月2日(星期五) 晚上7:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiejunping/andt-components] 大佬，我用react重新写了下发现如下图问题 (#3)

**Comment by ISBN9527** [comment]
> 这应该是样式问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xiejunping/andt-components" ***@***.***&gt;; 发送时间:&nbsp;2021年7月2日(星期五) 晚上7:18 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[xiejunping/andt-components] 大佬，我用react重新写了下发现如下图问题 (#3) 上下有偏移可能是什么问题呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

已解决，样式问题哈
